# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZRC'S ZONE
email: 1993.zrc@gmail.com
description:  A virtual proof that I'm awesome
#baseurl: "/zhang-rongchen.github.io" # the subpath of your site, e.g. /blog
#baseurl: "/zrc" # the subpath of your site, e.g. /blog
#url: "http://zhang-rongchen.github.io" # the base hostname & protocol for your site
github_username:  zhang-rongchen

# Build settings
markdown: kramdown
